code --install-extension IBM.output-colorizer
code --install-extension alefragnani.project-manager
code --install-extension bierner.color-info
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.git-extension-pack
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension himanoa.Python-autopep8
code --install-extension HookyQR.beautify
code --install-extension jasonnutter.search-node-modules
code --install-extension jawandarajbir.react-vscode-extension-pack
code --install-extension jumpinjackie.vscode-map-preview
code --install-extension lextudio.restructuredtext
code --install-extension matangover.mypy
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension naumovs.color-highlight
code --install-extension Orta.vscode-jest
code --install-extension Prisma.vscode-graphql
code --install-extension ryanluker.vscode-coverage-gutters
code --install-extension shaharkazaz.git-merger
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.ReactSnippets
code --install-extension ziyasal.vscode-open-in-github